# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: busybox:latest

before_script:
  - echo "Before script section"
  - kubectl delete configmap prometheussss -n prod || echo 1
  - kubectl create configmap prometheussss --from-file=configmap/  -n prod
   
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
   
build1:
  tags:
  - master-shell
  stage: build
  script:
    - kubectl apply -f prometheus-k8s.yaml -n prod
   
test1:
  stage: test
  tags:
  - master-shell
  script: 
    - echo "Do a test here"
    - echo "For example run a test suite"
   
test2:
  stage: test
  tags:
  - master-shell
  script: 
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
   
deploy1:
  stage: deploy
  tags:
  - master-shell
  script:
    - echo "Do your deploy here"
